### ISSUE TITLE
🌲 [Request] Better support for testing in a domain driven design application

### ISSUE THREAD

**Issue by AldasKleinas** [kenherring/ablunit-test-runner#224]
### Feature Request

Say an application is separated into multiple pairs of a domain implementation project and domain interface project i. e.
![image](https://github.com/user-attachments/assets/f21a0e27-80e8-425b-921b-8def097b8667)

The interface project here would utilize its implementation project to define how data from its' domain can be accessed from other domains.  Logically, the interface project should not have any direct connection to a database. However, currently, for it to be tested with ABLUnit, an interface project would need to have a database connection defined in its openedge-project.json file.

It would be useful if it was possible to somehow account for a situation like this in the ABLUnit configuration.

**Comment by kenherring** [comment]
Just want to make sure I'm understanding... the ask is that ABLUnit tests can be run with no database connection?

**Comment by mikefechner** [comment]
> the ask is that ABLUnit tests can be run with no database connection?

It's the opposite.

Consider two projects in a workspace: 

- XYZ-Implementation with a database connection
- XYZ-Interface with no database connection.

XYZ-Interface references XYZ-Implementation in the Propath.

When running an unit-test in XYZ-Interface project, the code that is tested my run test in the XYZ-Implementation project that relies on the database connection. So we need to understand how to configure the test-runtime for tests in XYZ-Interface to use a DB connection when the openedge-project.json for this project does not require the DB.

Hope that makes sense?

**Comment by kenherring** [comment]
Are these projects co-dependent or is XYZ-Interface dependent on XYZ-Implementation but not vice versa?  The reason I ask is usually terms "Implementation" and "Interface" imply that XYZ-Implementation would depend on XYZ-Interface but the reverse would not be true.  

> "XYZ-Interface references XYZ-Implementation in the Propath"

How would the database connection be made when executing this code at runtime if the XYZ-Interface project has no database connection?

Can you share details about how the test would execute outside of this extension?  Is there something specific to that environment that we could accommodate within this extension?

> So we need to understand how to configure the test-runtime for tests in XYZ-Interface to use a DB connection when the openedge-project.json for this project does not require the DB.

One idea would be to have the test connect to the database using the `CONNECT` statement in either the `@Before` or `@BeforeAll` method.

This extension also allows for executing tests using database connection(s) that differ from the active profile used by the OpenEdge ABL plugin which can be configured in `.vscode/ablunit-test-profile.json`.  There are two ways this might be accomplished:

1. Add a profile to `openedge-project.json` that defines the the database connection and reference the profile name in the extension configuration:
    ```json
    {
        "configurations": [{
            "openedgeProjectProfile": "testing with DB"
        }]
    }
    ```
2. Add the required parameters necessary to establish connection(s) when the `_progres` process launches using the `additionalArgs` field:
    ```json
    {
        "configurations": [{
           "command": {
                "additionalArgs": [
                    "-pf",
                    "path/to/dbconnections.pf"
                ]
            }
        }]
    }
    ```

Details regarding extension configuration can be found here: [`resources/ablunit-test-profile.detail.jsonc`](https://github.com/kenherring/ablunit-test-runner/blob/main/resources/ablunit-test-profile.detail.jsonc).  This file also appears in VSCode when you run the **Configure Test Profiles** command and no `.vsocde/ablunit-test-profile.json` exists.

Another idea would be to move the test case to the XYZ-Implementation project.  Theoretically unit tests should be testing small components specific to a project.  The requirement of the DB connection implies the test case might actually be testing functionality in the XYZ-Implementation project and would be better suited to execute from that project.  Practically speaking, I understand that code dependencies don't always make so easy.

A third idea would be to mock the XYZ-Implementation code required for this test.  The mock would allow validating behavior to a given response without actually executing the code to create the response, thus eliminating the DB connection required to execute the unit test and reducing the scope of code run during test execution.

---

Would it be possible to share a project so I can recreate the situation first-hand?  This seems like it could be more of a project architecture question and not specific to this extension, but I could be wrong.  Regardless, if there is functionality that can be added to this extension to help accommodate your use case I'm certainly interested in doing so.  A sample project would help me avoid guesswork and ensure any new functionality is accurate for your use case.

**Comment by mikefechner** [comment]
@kenherring thanks for that. We have managed to define a second profile with the DB connections in openedge-project.json and refer to that in the .vscode/abunit-test-profile.json

What bugs me is that the "configurations" array in that file only supports 0 or 1 entries. Is it possible to define multiple configurations (e.g. with small local and large remote databases) and switch them when running a test?

I do not want to select a new profile for the language server.

**Comment by kenherring** [comment]
The array annoys me too :D

It was originally put in place to work with a pre-release version of the VSCode testing api.  That specific functionality didn't make the final cut.

I've been wavering between a few options, or some combination of these options, which could make use of the array.

1. Remove the array so there is a singular configuration.
2. Allow multiple entries which define named "profiles".  A profile could be selected prior to test execution.
    * This would make it easier to run tests for all the environmental permutations the final product needs to function with.
4. Add `files.include` and `files.exclude` fields so that test cases within a project could execute with different config based on which array item was matched.  I'm not totally in love with this idea because it feels like doing so is bad practice, but I haven't completely written off the idea.
    * Using the `@BeforeAll` annotation or similar lifecycle functionality tends to result in more repeatable tests due to reduced outside dependency.
5. Add a `testRunProfileKind` with values `test`, `debug`, or `coverage`.  This would allow different configuration depending on which test run type is used.  I've been moving farther away from this with time though, preferring to let the extension be opinionated. The option is on the table though.

There is no immediate plan to change the config as I don't have a good reason to just yet.  I'd also like to see how the VSCode testing api evolves as that could affect what profiles are capable of.  That said, any feedback that would help drive the implementation is always welcome.

> multiple configurations (e.g. with small local and large remote databases)

Does this result in flaky tests, especially for the large remote (and presumably shared) databases?  My preference is to have developers run tests with exactly the same DBs which are spun up for CI/CD (a docker image containing DBs, or create an empty database from schema on the fly).  This ensures test results for a given commit are always the same (repeatability), and avoids the "works on my machine" problem.

My long term vision is to have a GitHub Action and/or CircleCI orb that can automatically run tests using the config defined for this extension.

**Comment by kenherring** [comment]
Closing for now as I believe you were able to configure this for your scenario, but feel free to re-open or log a new issue if necessary.
