### ISSUE TITLE
Add DB connection possibility (idealy from openedge-project.json)

### ISSUE THREAD

**Issue by PauliusKu** [kenherring/ablunit-test-runner#51]
I know, that the license you use does not allow DB connections, but it is important, because usually, many UTs needs DB access.

**Comment by kenherring** [comment]
Hey @PauliusKu, good to hear from you!  Hope all is well.

Good new!  DB connects work today - use the `ablunit.params` config with a `.pf` file.  Example:

```
  "ablunit.params": "-pf dbconnections.pf"
```

You can see this in one of the test cases for the extension here: https://github.com/kenherring/ablunit-test-provider/blob/main/test_projects/proj0/.vscode/settings.json#L2

After I get get version 1.0 out the door I'll be looking to import the connections from `openedge-project.json`, but it's not high on my priority list at the moment.

Can you see if this will work for you?  If so I'll close this issue, otherwise I'll add a test case for whatever is not working.

**Comment by kenherring** [comment]
Thia made it into the release: https://github.com/kenherring/ablunit-test-runner/releases/tag/0.2.0

Let me know if you have any trouble.
